version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile-wp
    image: my-wordpress-image
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: yourdbname
      WORDPRESS_DB_USER: yourdbuser
      WORDPRESS_DB_PASSWORD: yourdbpassword
    ports:
      - "8080:80"
    working_dir: /var/www/html
    volumes:
      - ./wordpress:/var/www/html

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data

  nginx:
    depends_on:
      - wordpress
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  db_data:
  wp_data:
  redis_data:
  jenkins_home:
